
name: Build locally on runner & Push to ACR
on:
  push:
    branches: [ "main" ]

env:
  ACR_NAME: dtcrtestregistrycentraluspoc
  ACR_LOGIN: dtcrtestregistrycentraluspoc-gxb3a0c4cddgayev.azurecr.io
  IMAGE_NAME: admindashboard
  IMAGE_TAG: v1.0.2

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Log in to ACR
      - name: Docker login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ACR_LOGIN }}
          username: ${{ secrets.ACR_USERNAME }}     # optional if using az acr login, but this is simple
          password: ${{ secrets.ACR_PASSWORD }}     # (enable Admin user on ACR to get these creds)

      # Build & push
      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.ACR_LOGIN }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
